version: '3.8'
services:
  client:
    build: ./front
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      # - ./app/node_modules
    stdin_open: true
    tty: true